import Link from 'next/link'
import { upcomingWorkshop, workshopCurriculum } from '@/lib/maria-business'

const formatDate = (value: string) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T12:00:00`))

export default function WorkshopsPage() {
  const session = upcomingWorkshop
  return (
    <main className="container workshop-page">
      <section className="workshop-hero">
        <div><span className="kicker">Sunday Perfumery Workshop</span><h1>Make your own signature fragrance.</h1><p>A hands-on Maria experience covering perfume basics, fragrance notes, blending and personal scent creation. Take your finished perfume home.</p><div className="hero-actions"><Link className="button primary" href="#book">Book Your Seat</Link><Link className="button" href="/events">Private & Group Workshops</Link></div></div>
        <aside className="workshop-ticket"><span>UPCOMING SUNDAY</span><strong>{formatDate(session.date)}</strong><b>{session.time}</b><small>₹1,200 per person · Bengaluru</small></aside>
      </section>
      <section className="workshop-grid">
        <article className="workshop-card"><span className="kicker">What you'll learn</span><h2>From notes to your own scent.</h2><ol>{workshopCurriculum.map((item, i) => <li key={item}><b>0{i + 1}</b>{item}</li>)}</ol></article>
        <article className="workshop-card workshop-dark"><span className="kicker">The experience</span><h2>Learn, blend, create, take it home.</h2><p>The workshop is held every Sunday at Maria Perfumes in Bengaluru. After completing the experience, participants receive a certificate.</p><div className="workshop-facts"><div><strong>₹1,200</strong><span>per person</span></div><div><strong>Sunday</strong><span>weekly session</span></div><div><strong>Certificate</strong><span>included</span></div></div></article>
      </section>
      <section id="book" className="workshop-booking"><div><span className="kicker">Reserve your place</span><h2>Book a Sunday seat.</h2><p>Choose the number of participants. Payment uses UPI and the booking stays pending until Maria manually verifies the transaction.</p></div><form action="/api/workshops/book" method="post" className="booking-form"><input type="hidden" name="sessionId" value={session.id} /><label>Full name<input name="name" required placeholder="Your name" /></label><label>WhatsApp / Phone<input name="phone" required placeholder="+91" /></label><label>Email<input name="email" type="email" placeholder="you@example.com" /></label><label>Participants<input name="participants" type="number" min="1" defaultValue="1" required /></label><button className="button primary" type="submit">Continue to UPI Booking</button></form></section>
      <section className="private-workshop"><span className="kicker">Private workshops</span><h2>Bring your own group.</h2><p>Birthday groups, corporate teams, college groups and private celebrations can request a dedicated Maria perfumery session.</p><Link href="/events#event-enquiry">Request a Private Workshop</Link></section>
      <style jsx>{`
        .workshop-page{padding-bottom:100px}.workshop-hero{padding:90px 0 70px;display:grid;grid-template-columns:1.15fr .85fr;gap:60px;align-items:center}.workshop-hero h1{font:400 clamp(48px,6vw,82px)/.95 var(--serif);margin:10px 0 20px;letter-spacing:-.04em}.workshop-hero p{max-width:650px;color:var(--muted);font-size:16px}.workshop-ticket{background:var(--wine);color:#fff;padding:42px;min-height:300px;display:flex;flex-direction:column;justify-content:center}.workshop-ticket span{font-size:10px;letter-spacing:.18em;color:#d8bb76}.workshop-ticket strong{font:400 36px var(--serif);margin:14px 0 5px}.workshop-ticket b{font-size:14px}.workshop-ticket small{color:#d9cbca;margin-top:10px}.workshop-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.workshop-card{background:#fff;border:1px solid var(--line);padding:38px}.workshop-card h2,.workshop-booking h2,.private-workshop h2{font:400 38px var(--serif);margin:10px 0 20px}.workshop-card ol{list-style:none;padding:0;margin:30px 0 0}.workshop-card li{display:flex;gap:18px;padding:17px 0;border-top:1px solid var(--line);font-size:14px}.workshop-card li b{font-size:10px;color:#927445}.workshop-dark{background:var(--ink);color:#fff;border-color:var(--ink)}.workshop-dark p{color:#d1c7c5}.workshop-dark .kicker{color:#d8bb76}.workshop-facts{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:35px}.workshop-facts div{border-top:1px solid rgba(255,255,255,.2);padding-top:14px}.workshop-facts strong,.workshop-facts span{display:block}.workshop-facts strong{font:400 20px var(--serif)}.workshop-facts span{font-size:10px;color:#b9afad;margin-top:4px}.workshop-booking{margin-top:70px;padding:70px 0;border-top:1px solid var(--line);display:grid;grid-template-columns:.8fr 1.2fr;gap:70px}.workshop-booking p{color:var(--muted);max-width:500px}.booking-form{display:grid;grid-template-columns:1fr 1fr;gap:14px}.booking-form label{font-size:10px;text-transform:uppercase;letter-spacing:.1em;display:grid;gap:6px}.booking-form input{border:1px solid #d9d0c6;background:#fff;padding:13px;font:inherit;color:var(--ink)}.booking-form button{grid-column:1/-1;margin-top:6px}.private-workshop{background:#eee7dc;padding:55px;margin-top:20px}.private-workshop p{color:var(--muted);max-width:600px}.private-workshop a{color:var(--wine);font-size:12px;text-transform:uppercase;letter-spacing:.1em}@media(max-width:800px){.workshop-hero,.workshop-grid,.workshop-booking{grid-template-columns:1fr}.workshop-hero{padding-top:55px}.workshop-ticket{min-height:240px}.booking-form{grid-template-columns:1fr}.workshop-facts{grid-template-columns:1fr}}
      `}</style>
    </main>
  )
}
