export type MariaFragrance = {
  name: string
  slug: string
  accords: { label: string; value: number }[]
  notes: string[]
  day: number
  night: number
  seasons: { label: string; value: number }[]
  mood: string
}

export const MARIA_PRICING = { 30: 600, 50: 1000, 100: 1800 } as const

export const MARIA_FRAGRANCES: MariaFragrance[] = [
  { name: 'Fucking Fabulous', slug: 'fucking-fabulous', accords: [{label:'Leather',value:96},{label:'Warm Spicy',value:84},{label:'Almond',value:66},{label:'Woody',value:58},{label:'Sweet',value:52}], notes:['Almond','Tonka Bean','Orris','Cashmeran','Leather','Clary Sage'], day:38, night:88, seasons:[{label:'Winter',value:88},{label:'Spring',value:28},{label:'Summer',value:18},{label:'Autumn',value:76}], mood:'Bold · sensual · warm' },
  { name: 'Oud Wood', slug: 'oud-wood', accords: [{label:'Woody',value:96},{label:'Warm Spicy',value:76},{label:'Amber',value:64},{label:'Oud',value:58},{label:'Earthy',value:48}], notes:['Rosewood','Cardamom','Oud','Sandalwood','Vetiver','Tonka Bean','Amber'], day:62, night:72, seasons:[{label:'Winter',value:76},{label:'Spring',value:46},{label:'Summer',value:38},{label:'Autumn',value:84}], mood:'Polished · woody · quietly luxurious' },
  { name: 'Ombré Leather', slug: 'ombre-leather', accords: [{label:'Leather',value:100},{label:'Woody',value:78},{label:'Amber',value:64},{label:'Floral',value:48},{label:'Warm Spicy',value:44}], notes:['Black Leather','Cardamom','Jasmine Sambac','Patchouli','White Moss','Amber'], day:42, night:92, seasons:[{label:'Winter',value:82},{label:'Spring',value:40},{label:'Summer',value:22},{label:'Autumn',value:96}], mood:'Dark · refined · magnetic' },
  { name: 'Tuscan Leather', slug: 'tuscan-leather', accords: [{label:'Leather',value:100},{label:'Fruity',value:58},{label:'Woody',value:56},{label:'Smoky',value:48},{label:'Warm Spicy',value:42}], notes:['Raspberry','Saffron','Thyme','Olibanum','Leather','Suede','Woody Notes'], day:36, night:94, seasons:[{label:'Winter',value:88},{label:'Spring',value:34},{label:'Summer',value:20},{label:'Autumn',value:94}], mood:'Intense · leathery · dramatic' },
  { name: 'Lost Cherry', slug: 'lost-cherry', accords: [{label:'Fruity',value:100},{label:'Sweet',value:86},{label:'Almond',value:62},{label:'Woody',value:44},{label:'Warm Spicy',value:38}], notes:['Black Cherry','Bitter Almond','Cherry Liqueur','Tonka Bean','Peru Balsam','Roasted Tonka'], day:64, night:82, seasons:[{label:'Winter',value:70},{label:'Spring',value:64},{label:'Summer',value:54},{label:'Autumn',value:86}], mood:'Luscious · playful · addictive' },
  { name: 'Café Rose', slug: 'cafe-rose', accords: [{label:'Floral',value:92},{label:'Rose',value:86},{label:'Woody',value:64},{label:'Warm Spicy',value:56},{label:'Coffee',value:42}], notes:['Turkish Rose','Bulgarian Rose','Coffee','Saffron','Patchouli','Amber'], day:58, night:82, seasons:[{label:'Winter',value:68},{label:'Spring',value:84},{label:'Summer',value:48},{label:'Autumn',value:76}], mood:'Romantic · sophisticated · mysterious' },
  { name: 'Black Orchid', slug: 'black-orchid', accords: [{label:'Floral',value:88},{label:'Earthy',value:78},{label:'Woody',value:72},{label:'Warm Spicy',value:58},{label:'Dark',value:52}], notes:['Black Truffle','Ylang Ylang','Bergamot','Black Orchid','Patchouli','Incense','Sandalwood'], day:42, night:90, seasons:[{label:'Winter',value:86},{label:'Spring',value:42},{label:'Summer',value:26},{label:'Autumn',value:94}], mood:'Opulent · dark · iconic' },
  { name: 'Noir Extreme', slug: 'noir-extreme', accords: [{label:'Warm Spicy',value:92},{label:'Amber',value:84},{label:'Sweet',value:76},{label:'Woody',value:58},{label:'Citrus',value:32}], notes:['Mandarin','Cardamom','Nutmeg','Saffron','Kulfi','Amber','Vanilla','Sandalwood'], day:40, night:92, seasons:[{label:'Winter',value:92},{label:'Spring',value:40},{label:'Summer',value:20},{label:'Autumn',value:88}], mood:'Creamy · spicy · seductive' },
  { name: 'Bitter Peach', slug: 'bitter-peach', accords: [{label:'Fruity',value:96},{label:'Sweet',value:78},{label:'Warm Spicy',value:56},{label:'Woody',value:48},{label:'Amber',value:44}], notes:['Peach','Blood Orange','Rum','Cognac','Davana','Patchouli','Sandalwood','Tonka Bean'], day:58, night:78, seasons:[{label:'Winter',value:54},{label:'Spring',value:70},{label:'Summer',value:76},{label:'Autumn',value:80}], mood:'Juicy · sensual · provocative' },
  { name: 'Tobacco Vanille', slug: 'tobacco-vanille', accords: [{label:'Tobacco',value:100},{label:'Sweet',value:92},{label:'Vanilla',value:88},{label:'Warm Spicy',value:62},{label:'Woody',value:54}], notes:['Tobacco Leaf','Spicy Notes','Vanilla','Cacao','Tonka Bean','Dry Fruits','Woody Notes'], day:34, night:94, seasons:[{label:'Winter',value:96},{label:'Spring',value:38},{label:'Summer',value:16},{label:'Autumn',value:94}], mood:'Rich · warm · comforting' },
  { name: 'Pancholi Absolute', slug: 'pancholi-absolute', accords: [{label:'Earthy',value:96},{label:'Woody',value:82},{label:'Balsamic',value:64},{label:'Warm Spicy',value:54},{label:'Green',value:42}], notes:['Patchouli Absolute','Earthy Woods','Balsamic Facets','Warm Spices','Dry Woods'], day:56, night:74, seasons:[{label:'Winter',value:76},{label:'Spring',value:50},{label:'Summer',value:34},{label:'Autumn',value:88}], mood:'Earthy · deep · meditative' },
  { name: 'Grey Vetiver', slug: 'grey-vetiver', accords: [{label:'Woody',value:92},{label:'Citrus',value:72},{label:'Aromatic',value:68},{label:'Earthy',value:58},{label:'Fresh',value:52}], notes:['Grapefruit','Orange Blossom','Nutmeg','Vetiver','Oakmoss','Woods'], day:86, night:48, seasons:[{label:'Winter',value:48},{label:'Spring',value:82},{label:'Summer',value:92},{label:'Autumn',value:64}], mood:'Crisp · tailored · effortless' },
  { name: 'Neroli', slug: 'neroli', accords: [{label:'Citrus',value:96},{label:'Floral',value:82},{label:'Fresh',value:78},{label:'Green',value:54},{label:'Aromatic',value:44}], notes:['Neroli','Bergamot','Lemon','Orange Blossom','Lavender','Rosemary'], day:94, night:34, seasons:[{label:'Winter',value:28},{label:'Spring',value:92},{label:'Summer',value:100},{label:'Autumn',value:42}], mood:'Bright · fresh · Mediterranean' },
]

export const getMariaFragrance = (slug: string) => MARIA_FRAGRANCES.find((item) => item.slug === slug)
