const DEFAULT_PRODUCTS=[
{id:'maria-noir',name:'Maria Noir',category:'Eau de Parfum',gender:'Unisex',family:'Woody Amber',description:'A deep, polished fragrance built around warm woods, amber and a refined oud trail.',notes:['Oud','Amber','Sandalwood'],rating:4.8,reviews:42,badge:'Bestseller',active:true,featured:true,variants:[{id:'50ml',label:'50 ml',price:1499,stock:20},{id:'100ml',label:'100 ml',price:2299,stock:10}],image:''},
{id:'rose-velvet',name:'Rose Velvet',category:'Eau de Parfum',gender:'Women',family:'Floral',description:'Soft rose and jasmine wrapped in clean musk for an elegant everyday signature.',notes:['Rose','Jasmine','Musk'],rating:4.7,reviews:31,badge:'New',active:true,featured:true,variants:[{id:'50ml',label:'50 ml',price:1299,stock:18},{id:'100ml',label:'100 ml',price:1999,stock:8}],image:''},
{id:'amber-oud',name:'Amber Oud',category:'Attar',gender:'Unisex',family:'Oud',description:'Concentrated attar with a rich oud opening and a warm amber dry-down.',notes:['Oud','Amber','Leather'],rating:4.9,reviews:57,badge:'Best Rated',active:true,featured:true,variants:[{id:'12ml',label:'12 ml',price:899,stock:25},{id:'24ml',label:'24 ml',price:1499,stock:12}],image:''},
{id:'citrus-veil',name:'Citrus Veil',category:'Eau de Parfum',gender:'Unisex',family:'Citrus',description:'Bright bergamot and orange balanced by clean vetiver for a fresh signature.',notes:['Bergamot','Orange','Vetiver'],rating:4.6,reviews:24,badge:'Fresh',active:true,featured:false,variants:[{id:'50ml',label:'50 ml',price:1199,stock:17}],image:''},
{id:'midnight-musk',name:'Midnight Musk',category:'Eau de Parfum',gender:'Men',family:'Woody Musk',description:'A confident evening fragrance with smooth musk, cedar and earthy patchouli.',notes:['Musk','Patchouli','Cedar'],rating:4.8,reviews:36,badge:'Icon',active:true,featured:false,variants:[{id:'100ml',label:'100 ml',price:1899,stock:9}],image:''},
{id:'discovery-set',name:'Maria Discovery Set',category:'Discovery Set',gender:'Unisex',family:'Collection',description:'Five curated Maria signatures in a presentation-ready discovery collection.',notes:['Five signatures','Travel sizes'],rating:4.9,reviews:18,badge:'Gift Pick',active:true,featured:true,variants:[{id:'5-piece',label:'5-piece set',price:999,stock:30}],image:''}
];
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v)||0);
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
let PRODUCTS=readJSON('maria-products',DEFAULT_PRODUCTS);
const state={query:'',category:'All',sort:'featured',cart:readJSON('maria-cart',{})};
const saveProducts=()=>localStorage.setItem('maria-products',JSON.stringify(PRODUCTS));
const saveCart=()=>localStorage.setItem('maria-cart',JSON.stringify(state.cart));
const getProduct=id=>PRODUCTS.find(p=>p.id===id&&p.active!==false);
const productVariant=(p,id)=>p?.variants?.find(v=>v.id===id)||p?.variants?.[0];
const productImage=p=>p?.image?`<img src="${p.image}" alt="${p.name} perfume" loading="lazy">`:`<div class="image-placeholder"><span>MARIA PERFUMES</span><small>Owner image upload</small></div>`;
const cartItems=()=>Object.entries(state.cart).map(([key,qty])=>{const [id,variantId]=key.split('::');const product=getProduct(id);const variant=productVariant(product,variantId);return product&&variant?{product,variant,qty}:null}).filter(Boolean);
const cartCount=()=>cartItems().reduce((n,x)=>n+x.qty,0);
const cartTotal=()=>cartItems().reduce((n,x)=>n+x.variant.price*x.qty,0);
function productCard(p){const v=p.variants[0];return `<article class="product-card"><a class="product-media" href="product.html?id=${p.id}">${productImage(p)}<span class="badge">${p.badge||'Signature'}</span></a><div class="product-copy"><div class="eyebrow">${p.family} · ${p.category}</div><h3>${p.name}</h3><p>${p.notes.join(' · ')}</p><div class="product-row"><strong>${money(v.price)}</strong><button class="add-btn" data-add="${p.id}" data-variant="${v.id}">Add to bag</button></div><div class="rating">★ ${p.rating||'—'} <span>(${p.reviews||0})</span></div></div></article>`}
function renderProducts(){const grid=document.querySelector('#productGrid');if(!grid)return;let items=PRODUCTS.filter(p=>p.active!==false&&(state.category==='All'||p.category===state.category)&&`${p.name} ${p.family} ${p.notes.join(' ')}`.toLowerCase().includes(state.query.toLowerCase()));if(state.sort==='price-low')items.sort((a,b)=>a.variants[0].price-b.variants[0].price);if(state.sort==='price-high')items.sort((a,b)=>b.variants[0].price-a.variants[0].price);if(state.sort==='rating')items.sort((a,b)=>(b.rating||0)-(a.rating||0));grid.innerHTML=items.map(productCard).join('')||`<div class="empty-state">No fragrances match your search.</div>`;const count=document.querySelector('#resultCount');if(count)count.textContent=`${items.length} fragrances`}
function renderCart(){const list=document.querySelector('#cartItems');if(!list)return;const items=cartItems();list.innerHTML=items.length?items.map(({product:p,variant:v,qty})=>`<div class="cart-item"><div class="cart-thumb">${p.image?`<img src="${p.image}" alt="">`:'<span>MP</span>'}</div><div><strong>${p.name}</strong><small>${v.label} · ${money(v.price)}</small><div class="qty"><button data-minus="${p.id}::${v.id}">−</button><span>${qty}</span><button data-plus="${p.id}::${v.id}">+</button></div></div><strong>${money(v.price*qty)}</strong></div>`).join(''):`<div class="empty-state">Your bag is empty.</div>`;document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cartCount());const t=document.querySelector('#cartSubtotal');if(t)t.textContent=money(cartTotal())}
function addToCart(id,variantId){const p=getProduct(id),v=productVariant(p,variantId);if(!p||!v)return;const key=`${id}::${v.id}`;state.cart[key]=(state.cart[key]||0)+1;saveCart();renderCart();const d=document.querySelector('#cartDrawer');if(d)d.dataset.open='true'}
function changeQty(key,delta){state.cart[key]=(state.cart[key]||0)+delta;if(state.cart[key]<=0)delete state.cart[key];saveCart();renderCart()}
function openCart(){const d=document.querySelector('#cartDrawer');if(d){d.dataset.open='true';renderCart()}}
function closeCart(){const d=document.querySelector('#cartDrawer');if(d)d.dataset.open='false'}
function makeOrder(customer){const items=cartItems();const order={id:`MP-${Date.now().toString().slice(-8)}`,createdAt:new Date().toISOString(),status:'New',paymentStatus:'Not collected',customer,items:items.map(x=>({productId:x.product.id,name:x.product.name,variantId:x.variant.id,variant:x.variant.label,qty:x.qty,unitPrice:x.variant.price,total:x.variant.price*x.qty})),subtotal:cartTotal(),total:cartTotal()};const orders=readJSON('maria-orders',[]);orders.unshift(order);localStorage.setItem('maria-orders',JSON.stringify(orders));state.cart={};saveCart();return order}
function makeBooking(data){const bookings=readJSON('maria-bookings',[]);const booking={id:`EV-${Date.now().toString().slice(-8)}`,createdAt:new Date().toISOString(),status:'New',...data};bookings.unshift(booking);localStorage.setItem('maria-bookings',JSON.stringify(bookings));return booking}
function boot(){renderCart();document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();addToCart(b.dataset.add,b.dataset.variant)}));document.querySelectorAll('[data-plus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.plus,1)));document.querySelectorAll('[data-minus]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.minus,-1)))}
document.addEventListener('input',e=>{if(e.target.matches('#search')){state.query=e.target.value;renderProducts()}});
document.addEventListener('change',e=>{if(e.target.matches('#category')){state.category=e.target.value;renderProducts()}if(e.target.matches('#sort')){state.sort=e.target.value;renderProducts()}});
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){e.preventDefault();addToCart(add.dataset.add,add.dataset.variant)}if(e.target.closest('[data-cart-open]'))openCart();if(e.target.closest('[data-cart-close]'))closeCart();if(e.target.id==='cartBackdrop')closeCart()});
document.addEventListener('DOMContentLoaded',()=>{renderProducts();boot()});