'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, CreditCard, Loader2, ShieldCheck } from 'lucide-react'
import { buildUpiIntent } from '@/lib/real-checkout'

type CartItem = { id:string; product_name:string; variant_name:string; quantity:number; unit_price:number }
type Address = { recipient_name:string; phone:string; line1:string; line2:string; city:string; state:string; postal_code:string; country:string }
const emptyAddress: Address = { recipient_name:'', phone:'', line1:'', line2:'', city:'', state:'', postal_code:'', country:'India' }

export default function CheckoutClient(){
 const [items,setItems]=useState<CartItem[]>([]); const [address,setAddress]=useState(emptyAddress); const [order,setOrder]=useState<{id:string;total:number}|null>(null); const [utr,setUtr]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [submitted,setSubmitted]=useState(false)
 useEffect(()=>{fetch('/api/cart').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items??[])}).catch(()=>setError('Unable to load your cart.'))},[])
 const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.unit_price)*i.quantity,0),[items]); const required=['recipient_name','phone','line1','city','state','postal_code'] as const
 async function createOrder(){setError('');if(required.some(k=>!address[k].trim()))return setError('Please complete your delivery details.');if(!/^\d{6}$/.test(address.postal_code.trim()))return setError('Enter a valid 6-digit PIN code.');if(!/^[6-9]\d{9}$/.test(address.phone.trim()))return setError('Enter a valid 10-digit Indian mobile number.');setBusy(true);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shippingAddress:address})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Unable to create order.');setOrder({id:d.order.id,total:Number(d.order.total)})}catch(e){setError(e instanceof Error?e.message:'Unable to create order.')}finally{setBusy(false)}}
 async function submitUtr(){if(!order||utr.trim().length<6)return setError('Enter a valid UTR / transaction reference.');setBusy(true);setError('');try{const r=await fetch('/api/payments/reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:order.id,reference:utr.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error??'Unable to submit payment reference.');setSubmitted(true)}catch(e){setError(e instanceof Error?e.message:'Unable to submit payment reference.')}finally{setBusy(false)}}
 const upiId=process.env.NEXT_PUBLIC_MARIA_UPI_ID||''; const upiLink=order&&upiId?buildUpiIntent({upiId,payeeName:'Maria Perfumes',amount:order.total,orderId:order.id}):'#'
 if(!items.length&&!order)return <main className="container checkout-page"><Link href="/cart" className="back-link"><ArrowLeft size={16}/> Back to cart</Link><div className="empty-state"><h2>Your cart is empty</h2><Link className="button primary" href="/shop">Explore fragrances</Link></div></main>
 return <main className="container checkout-page"><Link href="/cart" className="back-link"><ArrowLeft size={16}/> Back to cart</Link><section className="checkout-layout"><div><span className="kicker">Secure checkout</span><h1>Complete your Maria order.</h1>{!order?<div className="checkout-card"><h2>Delivery details</h2><div className="form-grid">{(Object.keys(address) as (keyof Address)[]).filter(k=>k!=='country').map(k=><label key={k}>{k.replaceAll('_',' ')}<input value={address[k]} onChange={e=>setAddress(c=>({...c,[k]:e.target.value}))} placeholder={k==='postal_code'?'6-digit PIN code':k==='phone'?'10-digit mobile number':k.replaceAll('_',' ')} inputMode={k==='phone'||k==='postal_code'?'numeric':undefined}/></label>)}</div><button className="button primary" onClick={createOrder} disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<CreditCard size={16}/>} Create order & continue</button></div>:<div className="checkout-card"><h2>UPI payment</h2><p>Order <strong>{order.id}</strong> has been created. Inventory is reserved while payment is pending.</p>{upiId?<a className="button primary" href={upiLink}><CreditCard size={17}/> Pay ₹{order.total.toLocaleString('en-IN')} via UPI</a>:<div className="error-note">UPI payment is unavailable until NEXT_PUBLIC_MARIA_UPI_ID is configured.</div>}<div className="payment-reference"><label htmlFor="utr">After payment, enter your UTR / transaction ID</label><input id="utr" value={utr} onChange={e=>setUtr(e.target.value)} placeholder="UTR / transaction ID" inputMode="numeric"/><button className="button" onClick={submitUtr} disabled={utr.trim().length<6||busy||submitted}>{busy?'Submitting…':submitted?'Submitted':'Submit payment reference'}</button></div>{submitted&&<div className="success-note"><Check size={17}/> Payment reference submitted for manual verification.</div>}</div>}{error&&<div className="error-note">{error}</div>}</div><aside className="order-summary"><span className="kicker">Order summary</span>{items.map(i=><div className="summary-item" key={i.id}><span>{i.product_name} · {i.variant_name} × {i.quantity}</span><strong>₹{(Number(i.unit_price)*i.quantity).toLocaleString('en-IN')}</strong></div>)}<div className="summary-total"><span>Total</span><strong>₹{(order?.total??total).toLocaleString('en-IN')}</strong></div><div className="trust-note"><ShieldCheck size={18}/> UPI opens your banking app. Maria never sees your UPI PIN.</div></aside></section></main>
}
