'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, CreditCard, Loader2, ShieldCheck } from 'lucide-react'
import { buildUpiIntent } from '@/lib/real-checkout'

type CartItem = { id: string; product_name: string; variant_name: string; quantity: number; unit_price: number }
type Address = { recipient_name: string; phone: string; line1: string; line2: string; city: string; state: string; postal_code: string; country: string }
const emptyAddress: Address = { recipient_name: '', phone: '', line1: '', line2: '', city: '', state: '', postal_code: '', country: 'India' }

export default function CheckoutClient() {
  const [items, setItems] = useState<CartItem[]>([]); const [address, setAddress] = useState(emptyAddress); const [order, setOrder] = useState<{ id: string; total: number } | null>(null); const [utr, setUtr] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [verifiedSubmission, setVerifiedSubmission] = useState(false)
  useEffect(() => { fetch('/api/cart').then((r) => r.json()).then((data) => setItems(data.items ?? [])).catch(() => setError('Unable to load your cart.')) }, [])
  const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.unit_price) * item.quantity, 0), [items])
  const createOrder = async () => { setBusy(true); setError(''); const response = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ shippingAddress: address }) }); const data = await response.json(); if (!response.ok) setError(data.error ?? 'Unable to create order.'); else setOrder({ id: data.order.id, total: Number(data.order.total) }); setBusy(false) }
  const submitUtr = async () => { if (!order || !utr.trim()) return; const response = await fetch('/api/payments/reference', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ orderId: order.id, reference: utr.trim() }) }); const data = await response.json(); if (!response.ok) setError(data.error ?? 'Unable to submit payment reference.'); else setVerifiedSubmission(true) }
  const upiId = process.env.NEXT_PUBLIC_MARIA_UPI_ID || ''; const upiLink = order && upiId ? buildUpiIntent({ merchantUpiId: upiId, payeeName: 'Maria Perfumes', amount: order.total, orderId: order.id }) : '#'
  if (!items.length && !order) return <main className="container checkout-page"><Link href="/cart" className="back-link"><ArrowLeft size={16}/> Back to cart</Link><div className="empty-state"><h2>Your cart is empty</h2><Link className="button primary" href="/shop">Explore fragrances</Link></div></main>
  return <main className="container checkout-page"><Link href="/cart" className="back-link"><ArrowLeft size={16}/> Back to cart</Link><section className="checkout-layout"><div><span className="kicker">Secure checkout</span><h1>Complete your Maria order.</h1>{!order && <div className="checkout-card"><h2>Delivery details</h2><div className="form-grid">{(Object.keys(address) as (keyof Address)[]).filter((key) => key !== 'country').map((key) => <input key={key} value={address[key]} onChange={(e) => setAddress((current) => ({ ...current, [key]: e.target.value }))} placeholder={key === 'postal_code' ? '6-digit PIN code' : key.replace('_',' ')} inputMode={key === 'phone' || key === 'postal_code' ? 'numeric' : undefined} />)}</div><button className="button primary" onClick={createOrder} disabled={busy}>{busy ? <Loader2 className="spin" size={16}/> : <CreditCard size={16}/>} Create order & continue</button></div>}{order && <div className="checkout-card"><h2>UPI payment</h2><p>Order <strong>{order.id}</strong> has been created and inventory is reserved while payment is pending.</p><a className="button primary" href={upiLink} aria-disabled={!upiId}><CreditCard size={17}/> Pay ₹{order.total.toLocaleString('en-IN')} via UPI</a><div className="payment-reference"><label htmlFor="utr">After payment, enter your UTR / transaction ID</label><input id="utr" value={utr} onChange={(e) => setUtr(e.target.value)} placeholder="UTR / transaction ID"/><button className="button" onClick={submitUtr} disabled={!utr.trim() || verifiedSubmission}>Submit payment reference</button></div>{verifiedSubmission && <div className="success-note"><Check size={17}/> Payment reference submitted for manual verification.</div>}</div>}{error && <div className="error-note">{error}</div>}</div><aside className="order-summary"><span className="kicker">Order summary</span>{items.map((item) => <div className="summary-item" key={item.id}><span>{item.product_name} · {item.variant_name} × {item.quantity}</span><strong>₹{(Number(item.unit_price) * item.quantity).toLocaleString('en-IN')}</strong></div>)}<div className="summary-total"><span>Total</span><strong>₹{(order?.total ?? total).toLocaleString('en-IN')}</strong></div><div className="trust-note"><ShieldCheck size={18}/> UPI is handled by your banking app. Maria never sees your UPI PIN.</div></aside></section></main>
}
