"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Bag, Search, Sparkles } from "lucide-react";
import { supabaseBrowser } from "@/lib/supabase/browser";
import type { Product, CartItem } from "@/lib/types";
import { toast } from "sonner";

export default function Storefront(){
 const [products,setProducts]=useState<Product[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const {data,error}=await supabaseBrowser().from("products").select("*,product_images(*),product_variants(*)").eq("active",true).order("featured",{ascending:false}).order("created_at",{ascending:false});if(error)throw error;setProducts((data||[]) as Product[])}catch(e){toast.error(e instanceof Error?e.message:"Could not load fragrances")}finally{setLoading(false)}})()},[]);
 const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.family||""} ${p.gender||""}`.toLowerCase().includes(q.toLowerCase())),[products,q]);
 const add=(p:Product)=>{const v=p.product_variants?.find(x=>x.active&&x.stock>0);if(!v){toast.error("This fragrance is currently unavailable");return}const key="maria-cart";const old:CartItem[]=JSON.parse(localStorage.getItem(key)||"[]");const i=old.findIndex(x=>x.variantId===v.id);if(i>=0)old[i].quantity++;else old.push({productId:p.id,variantId:v.id,productName:p.name,variantLabel:v.label,price:Number(v.price),quantity:1,imageUrl:p.product_images?.[0]?.image_url});localStorage.setItem(key,JSON.stringify(old));toast.success(`${p.name} added to your bag`)};
 return <main><header className="sticky top-0 z-50 border-b border-[var(--line)] bg-[color-mix(in_srgb,var(--paper)_90%,transparent)] backdrop-blur-xl"><div className="container flex h-20 items-center justify-between"><Link href="/" className="font-display text-2xl tracking-[.08em]">MARIA <span className="text-[var(--gold)]">PERFUMES</span></Link><nav className="hidden gap-8 text-xs font-semibold uppercase tracking-[.12em] md:flex"><Link href="/shop">Shop</Link><Link href="/events">Events</Link><Link href="/about">Our story</Link><Link href="/dashboard">Owner</Link></nav><Link href="/checkout" className="btn btn-ghost"><Bag size={16}/> Bag</Link></div></header>
 <section className="relative min-h-[78vh] overflow-hidden bg-[#1b0b0d] text-white"><video className="absolute inset-0 h-full w-full object-cover opacity-50" autoPlay muted loop playsInline><source src="/hero-video.mp4" type="video/mp4"/></video><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/35 to-transparent"/><div className="container relative flex min-h-[78vh] items-center"><div className="max-w-2xl"><p className="eyebrow text-[#d8b77c]">BENGALURU · MARIA PERFUMES</p><h1 className="font-display mt-5 text-6xl leading-[.9] md:text-8xl">Wear the memory.<br/><i>Leave the trace.</i></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75">A considered fragrance collection of perfumes and attars, selected for people who prefer presence over noise.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/shop" className="btn btn-primary">Explore collection <ArrowRight size={15}/></Link><Link href="/events" className="btn border border-white/30 text-white">Fragrance experiences</Link></div></div></div></section>
 <section className="container py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">THE MARIA EDIT</p><h2 className="font-display mt-3 text-5xl">A quieter kind of luxury.</h2></div><div className="relative w-full md:w-80"><Search className="absolute left-4 top-3.5" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="input pl-11" placeholder="Search fragrance..."/></div></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{loading?[1,2,3].map(i=><div key={i} className="aspect-[4/5] animate-pulse rounded-3xl bg-[#e9e0d4]"/>):filtered.map(p=><article key={p.id} className="group"><Link href={`/product/${p.slug}`}><div className="placeholder overflow-hidden rounded-3xl">{p.product_images?.[0]?.image_url?<img src={p.product_images[0].image_url} alt={p.product_images[0].alt_text||p.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>:<span>{p.name.toUpperCase()}<br/><small className="opacity-60">OWNER IMAGE PENDING</small></span>}</div></Link><div className="flex items-start justify-between gap-4 pt-5"><div><p className="eyebrow">{p.family||"FRAGRANCE"}</p><h3 className="font-display mt-1 text-3xl">{p.name}</h3><p className="mt-1 text-sm text-black/55">{p.description||"A signature composition from Maria Perfumes."}</p></div><button onClick={()=>add(p)} className="btn btn-ghost shrink-0" aria-label={`Add ${p.name}`}><Bag size={15}/></button></div></article>)}</div>{!loading&&!filtered.length&&<div className="py-24 text-center"><Sparkles className="mx-auto mb-4"/><p className="font-display text-3xl">The collection is being curated.</p></div>}</section>
 <section className="bg-[var(--wine)] py-24 text-white"><div className="container grid gap-12 md:grid-cols-2 md:items-center"><div><p className="eyebrow text-[#d8b77c]">EVENT FRAGRANCE EXPERIENCES</p><h2 className="font-display mt-4 text-5xl">Make the scent part of the memory.</h2><p className="mt-5 max-w-lg leading-7 text-white/70">Live fragrance stalls, return gifts and curated scent bars for weddings, birthdays and private celebrations.</p><Link href="/events" className="btn mt-8 border border-white/25 text-white">Plan an experience <ArrowRight size={15}/></Link></div><div className="grid gap-3"><div className="glass rounded-3xl p-6 text-white"><b>Live fragrance stalls</b><p className="mt-2 text-sm text-white/60">Guests discover and select their scent in person.</p></div><div className="glass rounded-3xl p-6 text-white"><b>Return gifts</b><p className="mt-2 text-sm text-white/60">Presentation-ready fragrance gifting.</p></div></div></div></section>
 <footer className="container flex flex-col justify-between gap-4 py-10 text-xs text-black/50 md:flex-row"><span>© 2026 Maria Perfumes · Kammanahalli, Bengaluru</span><span>Perfume. Personal. Unmistakable.</span></footer></main>
}
